ServerName localhost

DocumentRoot /var/www/html/public

<Directory /var/www/html>
    AllowOverride All
    Require all granted
</Directory>

<Directory /var/www/html/public>
    AllowOverride All
    Require all granted
    Options -Indexes
</Directory>

ErrorLog /dev/stderr
CustomLog /dev/stdout combined
